config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'welcome#home'
  get '/about', to: 'welcome#about'
  resources :campaigns do
    resources :posts
  
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  after_create :to_facebook
  belongs_to :campaign
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 150}
  validates :body, presence: true, length: {minimum: 10, maximum: 5000}
  validates :campaign_id, presence: true

  def to_facebook
    
    if post_on_facebook == true
      self.user.fb_post_on_page(self.body)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user! 
  before_action :set_post, only: [ :show, :edit, :update, :destroy]
  before_action :find_campaign


  def index
    @posts = Post.all
    @posts_by_date = @posts.group_by { |post| post.post_date.to_date }
  end

  def show
    
  end

  def new
    
    @post = Post.new
  end

  def edit
    
  end

  
  def create
    
    @post = Post.new(post_params)
    @post.post_on_facebook = params[:post][:post_on_facebook] == "1"
    @post.campaign= @campaign
    @post.user = current_user

    #byebug
    respond_to do |format|
      if @post.save
        format.html { redirect_to campaign_path(@campaign.id), notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to campaign_path(@campaign.id), notice: 'Post error: {#@post.errors}' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to campaign_post_path(@campaign,@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to campaign_path(@campaign), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def user
      current_user
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def find_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end

    
    def post_params
      params.require(:post).permit(:title, :body, :post_date, :user_id, :post_on_facebook)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_cal-view.html.erb
<div id="calendar-posts" hidden>
    <%= calendar do |date| %>
            <%= date.day %>
            <% if @posts_by_date[date]  %>
                <ul>
                    <% @posts_by_date[date].each do |post| %>
                        <li><%= link_to post.title, campaign_post_path(post) %></li>
                    <% end %>
                </ul>
            <% end %>
    <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: [@campaign, @post], local: true, class:"form-horizontal") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "control-label" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body, class: "control-label mt-3" %><br>
    <%= form.text_area :body, cols: 50, rows: 15, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :post_date, class: "control-label mt-3" %>
    <%= form.datetime_select :post_date %>
  </div>

  <div class="field">
    <%= form.check_box(:post_on_facebook) %>
    <%= form.label(:post_on_facebook, "Post on facebook") %>
    <%# form.text_field :user_id.name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Post", class: "btn btn-outline-success mt-2 mb-3"  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='row justify-content-between' id='posts'>
<% @posts.each do |post| %>

    <div class="card text-white bg-secondary mb-3" style="max-width: 20rem;">
    <div class="card-header"><%= post.post_date %></div>
    <div class="card-body">
        <h4 class="card-title"><%= link_to post.title, campaign_post_path(@campaign, post) %></h4>
        <p class="card-text"> <%= truncate(post.body, length: 200) %>
            <div class='post-meta-details'>
                <small>Created by: <strong style="color:#c1c16c"><%= post.user.name if post.user%></strong> ,
                    <%= time_ago_in_words(post.created_at) %> ago, <br>
                        Last updated: <%= time_ago_in_words(post.updated_at) %> ago
                </small>
            </div>
        </p>
        <div class='post-actions'>
            <%= link_to 'Show post', campaign_post_path(@campaign, post), class: 'btn btn-sm btn-outline-primary' %>
            <%= link_to 'Edit post', edit_campaign_post_path(@campaign, post), class: 'btn btn-sm btn-outline-info' %> 
            <%= link_to 'Delete post', campaign_post_path(@campaign, post), method: :delete, 
                data: {confirm: 'You are about to delete this post, are you sure?'},
                class: "btn btn-sm btn-outline-danger" %>
        </div>
    </div>
    </div>

<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', @post.campaign %> 

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= render 'post' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', campaign_path(@campaign) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Post date:</strong>
  <%= @post.post_date %>
</p>

<%= link_to 'Back', campaign_path(@campaign) %>