config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'welcome#home'
  get '/about', to: 'welcome#about'
  resources :campaigns do
    resources :posts
  
  end
  
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    has_many :posts
    validates :name, presence: true

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
  end

  def show
    @posts = @campaign.posts.order(created_at: :desc)
    @post = Post.new()
    @posts_by_date = @posts.group_by { |post| post.post_date.to_date }
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :due_start, :due_end)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true, class:"form-horizontal") do |form| %>

  <%= render 'shared/errors', obj: @campaign %>

  <div class="field">
    <%= form.label :name, class:"col-form-label" %> <br>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :due_start %> <br>
    <%#form.datetime_local_field :due_start, class:"form-control"%>
    <%= form.datetime_select :due_start %>
  </div>

  <div class="field">
    <%= form.label :due_end %> <br>
    <%= form.datetime_select :due_end %>
  </div>

  <div class="actions"> <br>
    <%= form.submit 'Create Campaign', class: "btn btn-outline-success mb-3" %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table class="table table-hover table-info">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Due start</th>
      <th scope="col">Due end</th>
      <th scope="col" colspan="3" class="col-3">Actions</th>
      
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr class="table-secondary col-3">
        <td><%= campaign.name %></td>
        <td><%= campaign.due_start %></td>
        <td><%= campaign.due_end %></td>
        <td>
            <%= link_to campaign, class: "btn btn-sm btn-outline-info" do%>
                <i class="far fa-eye"></i>
                Show
            <% end %>
        </td>
        <td>
            <%= link_to edit_campaign_path(campaign), class: "btn btn-sm btn-outline-success" do%>
                <i class="fas fa-highlighter"></i>
                Edit
            <% end %>
        </td>
        <td>
            <%= link_to campaign, method: :delete, data: { confirm: 'Are you sure?' }, 
                class:"btn btn-sm btn-outline-danger" do%>
                <i class="far fa-trash-alt"></i>
                Delete
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '< Back', campaigns_path %> |
<%= link_to 'Edit', edit_campaign_path(@campaign) %> 

<p>
  <strong>Name:</strong>
  <%= @campaign.name %>
</p>

<p>
  <strong>Due start:</strong>
  <%= @campaign.due_start %>
</p>

<p>
  <strong>Due end:</strong>
  <%= @campaign.due_end %>
</p>

<small>
    Created <%= time_ago_in_words(@campaign.created_at) %> ago
  |
    Last edited <%= time_ago_in_words(@campaign.updated_at) %> ago
</small><br>

<h2>List Of Posts</h2>

<div class="form-group">
    <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="customSwitch1" checked="">
      <label class="custom-control-label" for="customSwitch1">Switch view</label>
    </div>
</div>



<%= render 'posts/post' %>

<%= render 'posts/cal-view' %>


<%= link_to 'New Post >', new_campaign_post_path(@campaign) %>

<script>
document.querySelector("#customSwitch1").addEventListener("click", () =>{
document.querySelector("#calendar-posts").toggleAttribute("hidden")
document.querySelector("#posts").toggleAttribute("hidden")
})
</script>