config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'welcome#home'
  get '/about', to: 'welcome#about'
  resources :campaigns do
    resources :posts
  
  end
  
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-5">
    <footer>
        <div class='social-note'>
            <small>
                &copy;2019. Social Media <br>Managment Tool
            </small>
        </div>
        
        
    </footer>
</nav>

app/views/layouts/_jumbotron.html.erb
<div class='jumbotron mt-3'>
    <div class='container'> 
        <h1>Manage Your Facebook, Twitter and Instagram</h1>
        <p>Welcome to the app, one simple tool to manage your social content <br><br>
            It's easy how to CREATE, EDIT and SCHEDULE, CONTROL, ANALYZE,
            and REPORT on all your social media activity in different
            social networks.
        </p> 
        <div class='progress'>
            <div class='progress-bar progress-bar-striped' style='width: 40%;'></div>
            <div class='progress-bar progress-bar-striped bg-warning' style='width: 10%;'></div>
            <div class='progress-bar progress-bar-striped bg-danger' style='width: 10%;'></div>
            <div class='progress-bar progress-bar-striped progress-bar-animated bg-success' style='width: 10%;'></div>
            <div class='progress-bar progress-bar-striped bg-info' style='width: 30%;'></div>

        </div> 
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-3">
  <a class="navbar-brand" href="#" style="color:#F7DF1E">Social Media Managment</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Campaigns', campaigns_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
    </ul>

      <div class='social-block'>
          <% if current_user %>
              <div>
                  <%= current_user.name %><br>
                  <%# image_tag(current_user.image) %>
              </div>
          <% end %>
          <% unless current_user %>
              <%= link_to user_facebook_omniauth_authorize_path do %>
              <i class="fab fa-facebook-f" style="color:white"></i>
              <% end %>
          <% else %>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fab fa-facebook" style="color:white"><small> Logout</small></i>
              <% end %>
          <% end %>
      </div>
      <div class='social-block'>
          
          <% unless current_user %>
              <%= link_to root_path do %>
              <i class="fab fa-instagram" style="color:white"></i>
              <% end %>
          <% else %>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fab fa-instagram" style="color:white"></i>
              <% end %>
          <% end %>
      </div>

      <div class='social-block'>
          
          <% unless current_user %>
              <%= link_to root_path do %>
              <i class="fab fa-twitter" style="color:white"></i>
              <% end %>
          <% else %>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fab fa-twitter-square" style="color:white"></i>
              <% end %>
          <% end %>
      </div>
      
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SommaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/sketchy/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#c1c16c">
    <%= render 'layouts/navbar' %>
    <div class='container'>
    <%= render 'layouts/jumbotron' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
    <hr> <%# ----THIS FOR DEBUGGING---- %>
    <%= debug(params) if Rails.env.development? %>
</html>